namespace RatEye
{
	public partial class Config
	{
		public partial class Processing
		{
			/// <summary>
			/// The Icon class contains parameters, used by the icon processing module.
			/// </summary>
			public class Icon
			{
				/// <summary>
				/// Use the static icons for template matching
				/// </summary>
				public bool UseStaticIcons;

				/// <summary>
				/// Use the icon cache, generated by the game, for template matching
				/// </summary>
				public bool UseDynamicIcons;

				/// <summary>
				/// If <see langword="true"/> all dynamic icons will be reloaded when
				/// the file at <see cref="Path.DynamicCorrelation"/> is being modified
				/// </summary>
				public bool WatchDynamicIcons;

				/// <summary>
				/// Create a new icon config instance based on the state of <see cref="Config.GlobalConfig"/>
				/// </summary>
				/// <param name="basedOnDefault">
				/// Base the state on the default config rather then <see cref="Config.GlobalConfig"/>
				/// </param>
				public Icon(bool basedOnDefault = false)
				{
					EnsureStaticInit();

					if (basedOnDefault)
					{
						SetDefaults();
						return;
					}

					var globalConfig = GlobalConfig.ProcessingConfig.IconConfig;

					UseStaticIcons = globalConfig.UseStaticIcons;
					UseDynamicIcons = globalConfig.UseDynamicIcons;
					WatchDynamicIcons = globalConfig.WatchDynamicIcons;
				}

				private void SetDefaults()
				{
					UseStaticIcons = false;
					UseDynamicIcons = false;
					WatchDynamicIcons = true;
				}

				internal static void SetStaticDefaults() { }

				internal void Apply() { }
			}
		}
	}
}
